### ISSUE TITLE
libthrfit dependency needs to be updated.

### ISSUE THREAD

**Issue by vinayvishal** [javaee/grizzly-thrift#4]
`grizzly-thrift` has got `libthrift` as dependency, however, the version being used is quite old.

```xml
<dependency>
  <groupId>org.apache.thrift</groupId>
  <artifactId>libthrift</artifactId>
  <version>0.9.1</version>
  <scope>provided</scope>
</dependency>
```
Last check-in to this version was done 4 yrs back. There are three more releases after that, the most recent being `0.10.0` which was released this year in Feb. `grizzly-thrift` build with `0.10.0` fails.

**Comment by carryel** [comment]
@vinayvishal Thanks for reporting this issue. I updated the libthrift and sources related to the library. Now `grizzly-thrift` build and testcases are fine.
