### ISSUE TITLE
Is there any problem with grizzly-framework-2.4.2?

### ISSUE THREAD

**Issue by deepsky777** [javaee/grizzly-thrift#5]
I wanna change grizzly core framework version. Before changing, I need to check grizzly-thrift-1.3.10 is compatible with  grizzly-framework-2.4.2.

**Comment by carryel** [comment]
@deepsky777 When I tested grizzly-framework-v2.4.x simply, I found compilation failure. Next week, I will try to resolve this issue.

**Comment by carryel** [comment]
@deepsky777 grizzly-thrift-1.3.11 will support that.

**Comment by deepsky777** [comment]
@carryel Thanks for it. I'll waiting for the next version.

**Comment by carryel** [comment]
@deepsky777 Sorry for late. I think it will be released with another patch until this week.

**Comment by carryel** [comment]
@deepsky777 I have just released v1.3.11. I think you can check it tomorrow.
