### ISSUE TITLE
grizzly-thrift 1.3.11 not available in Java 1.7?

### ISSUE THREAD

**Issue by darkman13** [javaee/grizzly-thrift#8]
i'm developing in Java 1.7
i can't compile with grizzly-thrift 1.3.11 

> Unsupported major.minor version 52.0

Is there a way to fix the problem?

**Comment by carryel** [comment]
@darkman13 Yes. Now v1.3.11 could be compiled at JDK 1.8 and above but JDK 1.7 could be used at runtime.
grizzly-thrift v1.3.11 uses grizzly-framework v2.4.2 which supports JDK 1.8 and above. (https://github.com/javaee/grizzly-thrift/issues/5)

I am sorry that I didn't notice about this. Could you upgrade JDK?
